name: unittest and docker build

on: [push]


jobs:
  build-n-publish:
  # should run on linux based operating system
    name: Unittest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Initialize Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run UnitTests
        run: python3 -m unittest -q
      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: python-day-calculator:latest