name: unittest and docker build

on: [push]

jobs:
  test-n-build:
    name: Unittest and Docker build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Initialize Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run UnitTests
        run: python3 -m unittest -q
      - name: Set up Docker
        id: buildx
        uses: docker/setup-buildx-action@v1
      # build, but not push for now
      - name: Build Docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: python-day-calculator:latest

       # add push to repo and deployment here
